      
### others
report_to: wandb
run_name: dpo_reward_xrk_0606_7B_lora

### model
model_name_or_path: /mnt/bn/evalonly/model/Qwen2.5-VL-7B-Instruct
image_max_pixels: 50176
video_max_pixels: 16384


### method
stage: rm
do_train: true
finetuning_type: lora 
lora_rank: 8
lora_target: all
#freeze_vision_tower: true  # choices: [true, false]
#freeze_multi_modal_projector: true  # choices: [true, false]
#freeze_language_model: false  # choices: [true, false]
deepspeed: examples/deepspeed/ds_z3_offload_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
flash_attn: fa2
### dataset
dataset: product_dpo
template: qwen2_vl
cutoff_len: 15000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4


### output
output_dir: /mnt/bn/evalonly/LLaMA-Factory/save/A_0606_product_reward/7Blora_train
logging_steps: 1
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: true
enable_liger_kernel: True


### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
